### ISSUE TITLE
FYI - request for inclusion in Django

### ISSUE THREAD

**Issue by aaugustin** [squareweave/django-loaddata-stdin#2]
I think the behavior implemented by django-loaddata-stdin is generally useful and I suggested to add it to Django: https://code.djangoproject.com/ticket/27978. You may want to subscribe to updates to that ticket.

**Comment by aaugustin** [comment]
Closing, as the sole point of this issue was to notify maintainers.

**Comment by aaugustin** [comment]
A contributor proposed a pull request to Django based on django-loaddata-stdin:
https://github.com/django/django/pull/8255

That PR is currently on hold because of licensing concerns. We don't have a good way to maintain the "Copyright (c) 2016, Squareweave Pty Ltd" specifically for the bits of code ported from django-loaddata-stdin.

@danni Would it be acceptable for Squareweave Pty Ltd to waive their copyright on this library so we can include its functionality in Django?

If it is, I'm not too sure about what needs to be done to record their agreement, but I believe signing a Corporate Contributor License Agreement (https://www.djangoproject.com/foundation/cla/faq/) and saying on https://github.com/django/django/pull/8255 that Squareweave Pty Ltd is OK with that PR should do.

Sorry for bothering you and thank you very much! :-)

**Comment by G-Rath** [comment]
@aaugustin sorry for the really late response - let me know if there's anything you need for this; Squareweave has merged into Ackama and we've had some turnover in staff so some of these smaller repos got lost in the shuffle.

I'm happy to do license adjustments if it means someone will get use out of this (and other) packages :)

**Comment by aaugustin** [comment]
I closed the issue because the code was merged in Django. I'm not sure how the discussion ended up. Anyway, nothing left to do here!
